name: my_app
description: A new Flutter project.

version: 1.0.0

environment:
  sdk: '>=3.2.0-42.2.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  adaptive_components: any
  intl: any
  file_picker: any
  firebase_core: any
  firebase_auth: any
  firebase_storage: any
  firebase_messaging: any
  shared_preferences: any
  cloud_firestore: any
  image_picker: 

flutter:
  uses-material-design: true
  assets:
    - img/